kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-pv-volume-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/k8sdata1/"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-pv-volume-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/k8sdata2/"